Q1: Which of the following is correct to create a 1-dimensional array from 0 to 9?

In [1]:
import numpy as np

# a
arr_a = np.arange(0, 10, 1)
print(arr_a)
# b
arr_b = np.arange(1, 10, 1)
print(arr_b)
# c
arr_c = np.arange(0, 9, 1)
print(arr_c)
# d
arr_d = np.arange(1, 11, 1)
print(arr_d)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]


Q2: Which of the following is correct to create a 3x3 boolean array with all values as True?

In [2]:
# a
arr_a = np.ones((3, 3)) > 0

# b
arr_b = np.ones((3, 3), dtype=bool)

# c
arr_c = np.full((3, 3), fill_value=True, dtype=bool)

# d
arr_d_a = np.ones((3, 3)) > 0
arr_d_b = np.ones((3, 3), dtype=bool)
arr_d_c = np.full((3, 3), fill_value=True, dtype=bool)

print(arr_a)
print(arr_b)
print(arr_c)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Q3: What is the output of the following code?

In [3]:
import numpy as np
arr = np.arange(0, 10)
print(arr[arr % 2 == 1])

[1 3 5 7 9]


Q4: What is the output of the following code?

In [4]:
import numpy as np
arr = np.arange(0, 10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Q5: What is the output of the following code?

In [5]:
import numpy as np
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Q6: What is the output of the following code?

In [6]:
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
print("Result:\n", c)

Result:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Q7: What is the output of the following code?

In [7]:
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
print("C =", c)

C = [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


Q8: What is the output of the following code?

In [8]:
import numpy as np
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


Q9: What is the output of the following code?

In [12]:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.nonzero((a >= 5) & (a <= 10))
print("result", a[index])

result [ 6  9 10]


Q10: What is the output of the following code?

In [13]:
import numpy as np

def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


Q11: What is the output of the following code?

In [14]:
import numpy as np

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
print("Result", np.where(a < b, b, a))

Result [6 7 9 8 9 7 5]
